### PR TITLE
Fixes language detection (check for pluralized navigator.language).

### PR DESCRIPTION
**Pull request by twanlass**
See issue: https://github.com/coderifous/jquery-localize/issues/56

### CODE REVIEW

**Comment by twanlass** [comment]
- Tests passing
- Tested in Firefox, Chrome and Safari latest (sorry, did not test IE)

**Comment by twanlass** [comment]
- Tests passing
- Tested in Firefox, Chrome and Safari latest (sorry, did not test IE)

**Comment by twanlass** [comment]
- Tests passing
- Tested in Firefox, Chrome and Safari latest (sorry, did not test IE)

**Comment by coderifous** [comment]
Thank you, Tyler.

**Pull request merged**
